#!/bin/bash

export BASE_GNOME_PACKAGES="\
	dconf-editor \
	epiphany \
	file-roller \
	gnome-browser-connector \
	gnome-console \
	gnome-control-center \
	gnome-disk-utility \
	gnome-keyring \
	gnome-session \
	gnome-shell \
	gnome-software \
	gnome-system-monitor \
	gnome-text-editor \
	gnome-tweaks \
	gnome-remote-desktop \
	gnome-shell-extensions \
	gnome-shell-extension-appindicator \
	gnome-shell-extension-desktop-icons-ng \
	gnome-menus \
	loupe \
	nautilus \
	nautilus-python \
	xdg-desktop-portal-gnome \
	xdg-user-dirs-gtk \
"

export EXTRA_GNOME_PACKAGES="\
	gnome-terminal \
	noto-fonts-cjk \
	papirus-icon-theme \
"

export BASE_GNOME_AUR_PACKAGES="\
	gnome-shell-extension-bluetooth-battery-meter-git \
	gnome-shell-extension-dash-to-dock \
	gnome-shell-extension-enhanced-osk-git \
	gnome-shell-extension-screen-autorotate \
	nautilus-copy-path \
	nautilus-open-any-terminal \
"

export BASE_GNOME_LOCAL_PACKAGES="\
	gnome-shell-extension-blur-my-shell \
	gnome-shell-extension-hibernate-status-git \
	gnome-shell-extension-logo-menu \
	steamdeck-gnome-presets \
"