#!/bin/bash

export BASE_PACKAGES="\
	aria2 \
	bat \
	bluez-utils \
	btop \
	cmake \
	ddcutil \
	cage \
	expect \
	exfatprogs \
	fastfetch \
	fd \
	freerdp \
	fzf \
	f2fs-tools \
	gparted \
	haveged \
	ibus-libpinyin \
	ibus-table-chinese \
	ibus-anthy \
	ibus-hangul \
	ibus-rime \
	jq \
	lib32-libva \
	lib32-libva-intel-driver \
	libcec \
	libdisplay-info \
	libva-intel-driver \
	lzip \
	nmon \
	ntfs-3g \
	otf-fira-mono \
	otf-fira-sans \
	otf-font-awesome \
	patch \
	plymouth \
	podman-compose \
	podman-docker \
	python-pyclip \
	python-pyudev \
	python-systemd \
	ripgrep \
	screen \
	scx-scheds \
	smartmontools \
	switcheroo-control \
	s-tui \
	ttf-dejavu \
	v2ray \
	wlr-randr \
	xdelta3 \
	xorg-xinit \
	xorg-server-xvfb \
	zoxide \
	zsh \
"

export EXTRA_PACKAGES="\
	antimicrox \
	imagemagick \
	lact-libadwaita \
	mission-center \
	mpv \
	openrgb \
	poppler \
	remmina \
	solaar \
	yazi \
"

export BASE_PACKAGES="$BASE_PACKAGES $EXTRA_PACKAGES"

export NVDIA_PACKAGES="\
	nvidia-open-dkms \
	opencl-nvidia \
	lib32-opencl-nvidia \
	nvidia-utils \
	lib32-nvidia-utils \
	nvidia-prime \
"

export BASE_AUR_PACKAGES="\
	lib32-extest \
	nbfc-linux \
	noto-fonts-cjk-fontconfig \
	onedrive-abraunegg \
	sx \
	vboard \
"

export EXTRA_AUR_PACKAGES="\
	flatseal \
	moonlight-qt-axi \
	protonplus \
	protontricks \
	tsukimi-bin \
"

export BASE_AUR_PACKAGES="$BASE_AUR_PACKAGES $EXTRA_AUR_PACKAGES"

export BASE_LOCAL_PACKAGES="\
	ayaneo-platform-dkms-git \
	clipboard-sync \
	davfs2 \
	mangohud-git \
	powerstation-git \
	rtl88x2bu-dkms-git \
	skorionos-fastfetch-logo \
	steam-launch-manager \
	steam-removable-media-git \
	steamos-manager \
	steamos-powerbuttond \
	xonedo-dkms \
	xonedo-firmware \
"