#!/bin/bash

export BASE_KDE_PACKAGES="\
	ark \
	bluedevil \
	breeze-gtk \
	deepin-wallpapers \
	discover \
	dolphin \
	dolphin-plugins \
	falkon \
	fcitx5-im \
	fcitx5-chinese-addons \
	flatpak-kcm \
	gwenview \
	kate \
	kde-gtk-config \
	kdeconnect \
	kdeplasma-addons \
	kfind \
	kgamma \
	kinfocenter \
	konsole \
	kpipewire \
	kscreen \
	ksshaskpass \
	kwallet-pam \
	kwalletmanager \
	onboard \
	partitionmanager \
	plasma-browser-integration \
	plasma-desktop \
	plasma-disks \
	plasma-keyboard \
	plasma-nm \
	plasma-pa \
	plasma-systemmonitor \
	plasma-thunderbolt \
	plasma-vault \
	python-notify2 \
	qmlkonsole \
	spectacle \
	xdg-desktop-portal-gtk \
	xdg-desktop-portal-kde \
"

export EXTRA_KDE_PACKAGES="\
	krdc \
	krdp \
"

export BASE_KDE_AUR_PACKAGES="\
	plasma6-themes-vapor-steamos \
"

export BASE_KDE_LOCAL_PACKAGES="\
	steamdeck-kde-presets-simple \
"