#! /bin/bash

for base in base-*; do
	source $base
done

export POSTCOPY="\
	cinnamon \
	wallpapers/gnome-backgrounds \
	wallpapers/gnome-backgrounds-cachyos \
"

export SUB_PACKAGES="\
	$BASE_PACKAGES \
	cinnamon \
	cinnamon-session \
	cinnamon-settings-daemon \
	cinnamon-control-center \
	cinnamon-screensaver \
	cinnamon-translations \
	cinnamon-menus \
	cinnamon-desktop \
	dconf-editor \
	nemo \
	nemo-fileroller \
	nemo-image-converter \
	nemo-preview \
	nemo-terminal \
	metacity \
	xed \
	xreader \
	network-manager-applet \
	blueman \
	gnome-software \
	gnome-terminal \
	noto-fonts-cjk \
	touchegg \
	xdg-user-dirs-gtk \
"

export SUB_AUR_PACKAGES="\
	$BASE_AUR_PACKAGES \
	ibus-autostart \
	mint-themes \
	xviewer \
"

export SUB_LOCAL_PACKAGES="\
	$BASE_LOCAL_PACKAGES \
	mint-y-icons \
"

export SUB_PACKAGES_TO_DELETE="\
	gnome-desktop \
	mutter \
"

sub_postinstallhook() {
	systemctl enable touchegg

	{
		echo "export GTK_IM_MODULE=ibus"
		echo "export QT_IM_MODULE=ibus"
		echo "export XMODIFIERS=@im=ibus"
	} >>/etc/environment

	install -Dm755 -t /etc/skel/Desktop/ /usr/share/applications/{skorionos-session-return,sk-chos-tool}.desktop
}
