#! /bin/bash

for base in base-*; do
	source $base
done

export POSTCOPY="\
	gnome \
	gnome-extra \
	wallpapers/gnome-backgrounds \
	wallpapers/gnome-backgrounds-cachyos \
"

export SUB_PACKAGES="\
	$BASE_PACKAGES \
	$BASE_GNOME_PACKAGES \
	$EXTRA_GNOME_PACKAGES \
	npm \
"

export SUB_AUR_PACKAGES="\
	$BASE_AUR_PACKAGES \
	$BASE_GNOME_AUR_PACKAGES \
	cursor-bin \
	linuxqq \
	microsoft-edge-stable-bin \
	qqmusic-bin \
"

export SUB_LOCAL_PACKAGES="\
	$BASE_LOCAL_PACKAGES \
	$BASE_GNOME_LOCAL_PACKAGES \
"

export SUB_PACKAGES_TO_DELETE="\
"

sub_postinstallhook() {
	install -Dm755 -t /etc/skel/Desktop/ /usr/share/applications/{skorionos-session-return,sk-chos-tool}.desktop
}
