#! /bin/bash

for base in base-*; do
	source $base
done

export POSTCOPY="\
	plasma \
	skel \
	wallpapers/wallpapers \
"

export SUB_PACKAGES="\
	$BASE_PACKAGES \
	$BASE_KDE_PACKAGES \
"

export SUB_AUR_PACKAGES="\
	$BASE_AUR_PACKAGES \
	$BASE_KDE_AUR_PACKAGES \
"

export SUB_LOCAL_PACKAGES="\
	$BASE_LOCAL_PACKAGES \
	$BASE_KDE_LOCAL_PACKAGES \
"

export SUB_PACKAGES_TO_DELETE="\
	gnome-desktop \
	mutter \
"

sub_postinstallhook() {
	:
}